### ISSUE TITLE
 Invalid machine name

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/ciel#8]
Hello,

I try to run `ciel shell -i machine_name`, but have error, step:
https://pastebin.aosc.io/paste/UyC-d8cDAwJxazue7Rg4kA

version:
```
ciel 2.1.5
➜  ciel_work lsb_release -a && uname -a && systemctl --version
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux buster/sid
Release:	testing
Codename:	buster
Linux eat-x220i 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-11-02) x86_64 GNU/Linux
systemd 240
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Comment by liushuyu** [comment]
Please run `ciel doctor` under this directory and paste the output. You may find out the cause yourself.

**Comment by LionNatsu** [comment]
@liushuyu The reason is simple, systemd 340 uses more restrictive machine id rules now, which is equivalent to the host name rules. Dashes in machine id, one of the design of ciel to avoid naming conflicts between containers, is now simply doesn't match the naming convention.

**Comment by MingcongBai** [comment]
@LionNatsu So any plan to comply with the new requirements? AOSC OS will land Systemd 240 soon.

**Comment by liushuyu** [comment]
https://github.com/AOSC-Dev/ciel/blob/master/internal/container/instance/instance.go#L243

A quick'n'dirty way is to replace `_` with `-`

**Comment by LionNatsu** [comment]
@liushuyu Why? No, it is not dirty. It should be exactly done in the way you said, please do so. systemd describes machine IDs use the same format as host/domain names use now, with restrictive rules only allow `-` but not `_`. Would you do me a favour?

**Comment by LionNatsu** [comment]
Thank you adorable liushu fish ^_^
